name: Send Email Workflow Call Parent
on:
  workflow_call:
    inputs:
      job_status:
        required: true
        type: string
      result:
        required: false
        type: string
      enable_email:
        required: true
        type: boolean

jobs:

  send_email:
    permissions: write-all
      # contents: write

    runs-on: ubuntu-latest
    if: ${{ inputs.enable_email }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ACTIONS_ROLE }}
          aws-region: us-east-1
     
      - name: Send Email Notification
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ENVIRONMENT=$(gh api repos/${{ github.repository }}/deployments | jq -r '.[0].environment' )
          echo $ENVIRONMENT
          echo .11
          # if echo "${{ inputs.result }}" | jq empty 2>/dev/null; then
          RESULT_TITLE="list of users"
          echo "${{ inputs.result }}"
          echo .21
          LIST=$(echo '"${{ inputs.result }}"' | jq -c . | jq -r '.Users[].UserName')
          # LIST=$(echo "${{ inputs.result }}")
          echo .31
          echo $LIST
          echo .41
          # fi
          TIMESTAMP=$(date -u +'%Y-%m-%dT%H:%M:%S')
          echo .51
          echo $LIST
          if [[ "${{ inputs.job_status }}" == "success" ]]; then
            LINK=$(echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}")
            EMAIL_BODY="<p>GitHub Action <b>${{ github.workflow }}</b> executed in <b>success</b>.</p> <p>Repo: <b>${{ github.repository }}</b> </p> <p>Environment: <b>$ENVIRONMENT</b> </p><p> $LIST </p> <p>Finished timestamp: <b>$TIMESTAMP</b> </p> <p>GitHub Action Job URL: $LINK</p>"
            # EMAIL_TITLE="Success Alert - ${{ github.repository }} - $ENVIRONMENT GitHub Action ${{ github.workflow }}"
            EMAIL_TITLE="Success Alert- $RESULT_TITLE - GitHub Action ${{ github.repository }} - $ENVIRONMENT"
          elif [[ "${{ inputs.job_status }}" == "failure" ]]; then
            JOB_ID=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs | jq '.jobs[] | select(.conclusion == "failure") | .id')
            ERROR_LOG="$(gh api repos/${{ github.repository }}/actions/jobs/$JOB_ID/logs | grep error)"
            ERROR="${ERROR_LOG#*\[error\]}"
            LINK=$(echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/$JOB_ID")
            EMAIL_BODY="<p>GitHub Action <b>${{ github.workflow }}</b> executed in <b>failure</b>.</p> <p>Repo: <b>${{ github.repository }}</b> </p> <p>Environment: <b>$ENVIRONMENT</b> </p> <p>Error log: <b>$ERROR</b></p> <p>Finished timestamp: <b>$TIMESTAMP</b> </p> <p>GitHub Action Job URL: $LINK</p>"
            EMAIL_TITLE='Failure Alert - GitHub Action ${{ github.workflow }}'
          fi
          aws ses send-email \
            --from "${{ vars.FROM_ADDRESS }}" \
            --destination "ToAddresses=${{ vars.TO_ADDRESS }}" \
            --message "Subject={Data=$EMAIL_TITLE,Charset=utf-8},Body={Html={Data=$EMAIL_BODY,Charset=utf-8}}" \
            --region us-east-1

  # call-wf-success:
  #   needs: [send_email]
  #   if: ${{ success() }}
  #   uses: ./.github/workflows/call-email-workflow-child.yml
  #   secrets: inherit
  #   with:
  #     job_status: success
  #     enable_email: true