name: Send Email using Amazon SES
on:
  push:
    branches:
      - main

env:
  SEND_EMAIL: true
jobs:
  another_job:
    environment: staging
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Test Step
      run: |
        echo "Goodbye Cruel World"
        echo "Github job id: ${{ github.job }}"
        echo "Print environment"
        echo "Current environment: ${{ github.event.deployment.environment }} "

  another_job2:
    runs-on: ubuntu-latest
    needs: [another_job]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Test Step
      if: ${{ env.SEND_EMAIL == 'true' }}
      id: demo
      run: |
        echo "Goodbye Cruel World"
        echo "Github job id: ${{ github.job }}"

    - name: Test Step 2
      run: |
        echo "Github job id: ${{ github.job }}"
        echo "get some JSON:"
        gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs

  call-wf-success:
    needs: [another_job, another_job2]
    if: ${{ success() }}
    uses: ./.github/workflows/call-email-workflow.yml
    secrets: inherit
    with:
      job_status: success
      enable_email: true

  call-wf-failure:
    needs: [another_job, another_job2]
    if: ${{ failure() }}
    uses: ./.github/workflows/call-email-workflow.yml
    secrets: inherit
    with:
      job_status: failure
      enable_email: true